language: generic

services:
  - docker

stages:
  - name: build
    if: branch != master
  - name: build-and-push
    if: branch == master

jobs:
  include:
    - stage: build
      script:
      - export WORKER_IMAGE=koobz/crusher-worker:${TRAVIS_COMMIT:0:8}
      - cd worker
      - docker build -t $WORKER_IMAGE .
    - script:
      - export SERVER_IMAGE=koobz/crusher-server:${TRAVIS_COMMIT:0:8}
      - cd server
      - docker build -t $SERVER_IMAGE .
    - stage: build-and-push
      script:
      - export WORKER_IMAGE=koobz/crusher-worker:${TRAVIS_COMMIT:0:8}
      - cd worker
      - docker build -t $WORKER_IMAGE .
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push $WORKER_IMAGE
    - script:
      - export SERVER_IMAGE=koobz/crusher-server:${TRAVIS_COMMIT:0:8}
      - cd server
      - docker build -t $SERVER_IMAGE .
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push $SERVER_IMAGE
