apiVersion: skaffold/v1beta11
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: koobz/crusher-dev-server
      context: server
    - image: koobz/crusher-dev-worker
      context: worker
deploy:
  kustomize:
    path: deploy/env/dev
