apiVersion: skaffold/v1beta11
kind: Config
build:
  local: {}
  artifacts:
    - image: koobz/crusher-dev-server
      context: server
    - image: koobz/crusher-dev-worker
      context: worker
deploy:
  kubectl:
    manifests:
      - deploy/*.yml
