---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crusher-worker
  namespace: crusher
  labels:
    app: crusher
    component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crusher
      component: worker
  template:
    metadata:
      labels:
        app: crusher
        component: worker
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - image: koobz/crusher-worker:alpha
          name: crusher-worker
          imagePullPolicy: Always
          env:
            - name: CRUSHER_HOST
              value: http://crusher-server
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: crusher
                  key: SLACK_SIGNING_SECRET
            - name: SLACK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: crusher
                  key: SLACK_API_KEY
